site_name: Dataset Phenotypes
site_description: A ReadTheDocs site for working with the dataset-phenotypes repository
site_author: Eric Earl
site_url: https://bids-pheno.readthedocs.io

nav:
  About: index.md

  Data Sets:
    ABCD Study: ABCD_4.md
    ABIDE I: ABIDE_I.md
    ABIDE II: ABIDE_II.md
    Child Mind Institute Healthy Brain Network: HBN.md
    Human Connectome Project: HCP.md
    Nathan Kline Institute Rockland Sample: NKI.md
    Philadelphia Neurodevelopmental Cohort: PNC.md
    UK Biobank: UKB.md

theme:
  name: material

plugins:
  - search
