site_name: Dataset Phenotypes

docs_dir: docs

nav:
  - About: index.md

  - Data Sets:
    - ABCD Study: ABCD_4.md
    - ABIDE I: ABIDE_I.md
    - ABIDE II: ABIDE_II.md
    - Child Mind Institute Healthy Brain Network: HBN.md
    - Human Connectome Project: HCP_1200.md
    - Nathan Kline Institute Rockland Sample: NKI.md
    - Philadelphia Neurodevelopmental Cohort: PNC.md
    - UK Biobank: UKB.md

theme: material

plugins:
  - search
