site_name: Dataset Phenotypes

docs_dir: docs

nav:
  - About: index.md
  - Adolescent Brain Cognitive Development Study: ABCD_4.md
  - Autism Brain Imaging Data Exchange I: ABIDE_I.md
  - Autism Brain Imaging Data Exchange II: ABIDE_II.md
  - Child Mind Institute Healthy Brain Network: HBN.md
  - Human Connectome Project: HCP_1200.md
  - Nathan Kline Institute Rockland Sample: NKI.md
  - Philadelphia Neurodevelopmental Cohort: PNC.md
  - United Kingdom Biobank: UKB.md

theme: material

plugins:
  - search
